### ISSUE TITLE
Connect via RS232

### ISSUE THREAD

**Issue by epmsmid** [eavanvalkenburg/sia#35]
I have a Galaxy XL with a serial interface, which can interface with a PAC via SIA.
Is it possible to / simple to add a serial port to the connection methods?

Another option is possibly use ser2net to convert serial to IP. Do you happen to know if this is possible?
I don't know if the protocol via serial is the same as via IP. I expect encryption is not used. If this can be switched off, it possibly works.

Another question: What is the difference between you HA integration and the one of Cheaterdev, which you forked?

**Comment by eavanvalkenburg** [comment]
Hi, no idea whether or not it is doable to create a version that talks through serial, and I have no real easy to test it, but have a look at the underlying package pysiaalarm if you're up for that! 

The differences between my version and cheaterdev are numerous, to name a few, my version is much more complete with regards to the sia protocol, my version is async and therefore much faster and it follows all the ha guidance because I'm currently waiting for it to become a official component!
